spring:
  application:
    name: authentication-boilerplate
  datasource:
    url: jdbc:mysql://localhost:3306/auth_boilerplate
    username: root
    password: nam123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


secure:
  jwt:
    secret-key: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
    token-expire: 60000
    refreshToken-expire: 10080000
