

#### register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "wajonir941@lapeds.com",
  "password": "123456",
  "firstName": "Nam1",
  "lastName": "Vu2"
}

#### verify email
GET http://localhost:8080/api/v1/auth/verify-email?token=38796684-d0df-4157-b5f5-4ce0406b872c


#### authenticate
#POST http://localhost:8080/api/v1/auth/login
#Content-Type: application/json
#
#{
#  "email": "vuhoainam@gmail.com",
#  "password": "123456"
#}
#
#> {% client.global.set("auth_token", response.body.accessToken); %}




#### greeting
#GET http://localhost:8080/api/v1/auth/greeting
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2dWhvYWluYW1AZ21haWwuY29tIiwiaWF0IjoxNzE3OTE2ODE3LCJleHAiOjE3MTc5MTY4Nzd9.cGY3GKBq0C7dWIjdaxs84PlqnJQiYIJywyY-lgJLaC0
#### logout
#POST http://localhost:8080/api/v1/auth/logout
#Authorization: Bearer {{auth_token}}
#
#### refresh token
#POST http://localhost:8080/api/v1/auth/refresh_token
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2dWhvYWluYW1AZ21haWwuY29tIiwiaWF0IjoxNzE3OTEyODI1LCJleHAiOjE3MTc5MjI5MDV9.n6hO5ygEPnAt5PqS2KbXPI1eqwx2oe_OrVFdJKQuRYE


###